In [1]:
#importando a biblioteca numpy com apelido np
import numpy as np

In [6]:
# criando um array convertendo de uma lista.
my_list1 = [1,2,3,4]


In [8]:
# crio um novo array a partir da lista anterior
my_array1 = np.array(my_list1)

In [9]:
my_array1

array([1, 2, 3, 4])

In [10]:
my_list2 = [11,22,33,44]

In [11]:
# Uma nova lista combinada com as duas anteriores
my_lists = [my_list1,my_list2]

In [12]:
# então posso criar um array multidimensional (matrz)
my_array_2 = np.array(my_lists)

In [13]:
my_array_2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
# Qual é o shape do array ?
my_array_2.shape

(2, 4)

In [16]:
# qual tipo de dados do array ?
my_array_2.dtype

dtype('int32')

#### Vetores Especiais

In [18]:
np.zeros(5) # Gera um vetor unidimensional com 5 indices com valor zero do tipo float

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
np.ones([5,5]) # Gera um vetor multidimensional. No caso bidimensional com 5 linhas e 5 colunas com valor um tipo float

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.empty(5) # Gera um vetor unidimensional com 5 indices com valor zero do tipo float

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
'''
    Gera uma Matriz Identidade, um vetor multidimensional com 5 linhas e 5 colunas com valor 1 para cada elemento 
    da diagonal principal e tipo float
'''
np.eye(5) 

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

#### Sequenciais

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])